from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors

from reportlab.lib.styles import (
    getSampleStyleSheet
)

from reportlab.lib.pagesizes import A4

from reportlab.platypus.flowables import (
    HRFlowable
)

from datetime import datetime


def generate_pdf(
    filename,
    task,
    subtasks,
    total_hours,
    total_amount
):

    doc = SimpleDocTemplate(
        filename,
        pagesize=A4,
        rightMargin=35,
        leftMargin=35,
        topMargin=30,
        bottomMargin=30
    )

    styles = getSampleStyleSheet()

    elements = []

    # ==================================================
    # HEADER
    # ==================================================

    title = Paragraph(
        """
        <font size=24 color="#1D4ED8">
        <b>TIME TRACKING REPORT</b>
        </font>
        """,
        styles['Title']
    )

    subtitle = Paragraph(
        """
        <font size=11 color="#6B7280">
        Generated by Time Tracker
        </font>
        """,
        styles['BodyText']
    )

    generated_time = Paragraph(
        f"""
        <font size=10 color="#374151">
        Generated: {datetime.now().strftime("%d %b %Y %I:%M %p")}
        </font>
        """,
        styles['BodyText']
    )

    elements.append(title)

    elements.append(subtitle)

    elements.append(Spacer(1, 8))

    elements.append(generated_time)

    elements.append(Spacer(1, 18))

    elements.append(
        HRFlowable(
            width="100%",
            thickness=1.2,
            color=colors.HexColor("#2563EB")
        )
    )

    elements.append(Spacer(1, 20))

    # ==================================================
    # CLIENT INFO
    # ==================================================

    client_info = [

        [
            Paragraph(
                "<b>Client</b>",
                styles['BodyText']
            ),

            task["client_name"]
        ],

        [
            Paragraph(
                "<b>Main Task</b>",
                styles['BodyText']
            ),

            task["task_name"]
        ],

        [
            Paragraph(
                "<b>Hourly Rate</b>",
                styles['BodyText']
            ),

            f"${task['hourly_rate']}/hr"
        ]
    ]

    client_table = Table(
        client_info,
        colWidths=[140, 330]
    )

    client_table.setStyle(TableStyle([

        (
            'BACKGROUND',
            (0, 0),
            (0, -1),
            colors.HexColor('#EFF6FF')
        ),

        (
            'TEXTCOLOR',
            (0, 0),
            (-1, -1),
            colors.black
        ),

        (
            'FONTNAME',
            (0, 0),
            (-1, -1),
            'Helvetica'
        ),

        (
            'FONTSIZE',
            (0, 0),
            (-1, -1),
            11
        ),

        (
            'BOTTOMPADDING',
            (0, 0),
            (-1, -1),
            10
        ),

        (
            'TOPPADDING',
            (0, 0),
            (-1, -1),
            10
        ),

        (
            'GRID',
            (0, 0),
            (-1, -1),
            0.5,
            colors.HexColor("#D1D5DB")
        ),

    ]))

    elements.append(client_table)

    elements.append(Spacer(1, 22))

    # ==================================================
    # SUMMARY BOX
    # ==================================================

    summary_data = [[

        Paragraph(
            f"""
            <font size=11 color="#2563EB">
            <b>TOTAL HOURS</b>
            </font>
            <br/><br/>
            <font size=20>
            <b>{total_hours}</b>
            </font>
            """,
            styles['BodyText']
        ),

        Paragraph(
            f"""
            <font size=11 color="#059669">
            <b>FINAL AMOUNT</b>
            </font>
            <br/><br/>
            <font size=20>
            <b>${total_amount}</b>
            </font>
            """,
            styles['BodyText']
        )

    ]]

    summary_table = Table(
        summary_data,
        colWidths=[235, 235]
    )

    summary_table.setStyle(TableStyle([

        (
            'BACKGROUND',
            (0, 0),
            (-1, -1),
            colors.HexColor("#F8FAFC")
        ),

        (
            'BOX',
            (0, 0),
            (-1, -1),
            1,
            colors.HexColor("#E5E7EB")
        ),

        (
            'BOTTOMPADDING',
            (0, 0),
            (-1, -1),
            18
        ),

        (
            'TOPPADDING',
            (0, 0),
            (-1, -1),
            18
        ),

        (
            'LEFTPADDING',
            (0, 0),
            (-1, -1),
            20
        )

    ]))

    elements.append(summary_table)

    elements.append(Spacer(1, 30))

    # ==================================================
    # SECTION TITLE
    # ==================================================

    work_title = Paragraph(
        """
        <font size=16 color="#1D4ED8">
        <b>WORK LOG DETAILS</b>
        </font>
        """,
        styles['Heading2']
    )

    elements.append(work_title)

    elements.append(Spacer(1, 10))

    elements.append(
        HRFlowable(
            width="100%",
            thickness=1,
            color=colors.HexColor("#2563EB")
        )
    )

    elements.append(Spacer(1, 14))

    # ==================================================
    # TABLE
    # ==================================================

    data = [[
        "#",
        "Subtask",
        "Description",
        "Start",
        "End",
        "Hours"
    ]]

    subtasks = sorted(
        subtasks,
        key=lambda x: x["start_time"]
    )

    for index, sub in enumerate(
        subtasks,
        start=1
    ):

        hours = round(
            (sub["total_seconds"] or 0) / 3600,
            2
        )

        start = datetime.strptime(
            sub["start_time"],
            "%Y-%m-%d %H:%M:%S"
        ).strftime("%d %b %I:%M %p")

        end = datetime.strptime(
            sub["end_time"],
            "%Y-%m-%d %H:%M:%S"
        ).strftime("%d %b %I:%M %p")

        data.append([

            str(index),

            Paragraph(
                sub["subtask_name"],
                styles['BodyText']
            ),

            Paragraph(
                sub["description"],
                styles['BodyText']
            ),

            start,

            end,

            str(hours)

        ])

    table = Table(
        data,
        colWidths=[30, 90, 160, 90, 90, 45]
    )

    style = [

        (
            'BACKGROUND',
            (0, 0),
            (-1, 0),
            colors.HexColor('#1D4ED8')
        ),

        (
            'TEXTCOLOR',
            (0, 0),
            (-1, 0),
            colors.white
        ),

        (
            'FONTNAME',
            (0, 0),
            (-1, 0),
            'Helvetica-Bold'
        ),

        (
            'FONTSIZE',
            (0, 0),
            (-1, 0),
            10
        ),

        (
            'FONTNAME',
            (0, 1),
            (-1, -1),
            'Helvetica'
        ),

        (
            'FONTSIZE',
            (0, 1),
            (-1, -1),
            9
        ),

        (
            'LEADING',
            (0, 1),
            (-1, -1),
            13
        ),

        (
            'GRID',
            (0, 0),
            (-1, -1),
            0.5,
            colors.HexColor("#D1D5DB")
        ),

        (
            'BOTTOMPADDING',
            (0, 0),
            (-1, -1),
            8
        ),

        (
            'TOPPADDING',
            (0, 0),
            (-1, -1),
            8
        ),

        (
            'VALIGN',
            (0, 0),
            (-1, -1),
            'MIDDLE'
        )

    ]

    # zebra rows

    for row in range(1, len(data)):

        bg = (
            colors.white
            if row % 2 == 0
            else colors.HexColor("#F9FAFB")
        )

        style.append((
            'BACKGROUND',
            (0, row),
            (-1, row),
            bg
        ))

    table.setStyle(TableStyle(style))

    elements.append(table)

    elements.append(Spacer(1, 28))

    # ==================================================
    # FOOTER NOTE
    # ==================================================

    note = Paragraph(
        """
        <font size=10 color="#374151">
        Thank you for your business.<br/>
        If you have any questions regarding this report,
        please feel free to reach out.
        </font>
        """,
        styles['BodyText']
    )

    elements.append(note)

    elements.append(Spacer(1, 20))

    footer = Paragraph(
        """
        <font size=9 color="#6B7280">
        Generated using Time Tracker
        •
        Confidential Work Activity Report
        </font>
        """,
        styles['BodyText']
    )

    elements.append(footer)

    # ==================================================
    # BUILD PDF
    # ==================================================

    doc.build(elements)